#pragma once
#include<iostream>
#include<tchar.h>
#include<Windows.h>
#include<process.h>
#include<DbgHelp.h>
#include<winternl.h>

#pragma comment(lib,"Dbghelp.lib")
#define ENUMDRIVER CTL_CODE(FILE_DEVICE_UNKNOWN,0x801,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define EnumDriver  2
#define HIDEDRIVER CTL_CODE(FILE_DEVICE_UNKNOWN,0x802,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define HideDriver  3
#define ENUMPROCESS CTL_CODE(FILE_DEVICE_UNKNOWN,0x803,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define EnumProcess 4
#define HIDEPROCESS CTL_CODE(FILE_DEVICE_UNKNOWN,0x804,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define HideProcess 5
#define MYKILLPROCESS CTL_CODE(FILE_DEVICE_UNKNOWN,0x805,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define MyKillProcess 6
#define ENUMTHREAD CTL_CODE(FILE_DEVICE_UNKNOWN,0x806,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define EnumThread 7
#define ENUMMODULE CTL_CODE(FILE_DEVICE_UNKNOWN,0x807,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define EnumModule 8
#define ENUMFILE CTL_CODE(FILE_DEVICE_UNKNOWN,0x808,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define EnumFile 1
#define DELETEFILE CTL_CODE(FILE_DEVICE_UNKNOWN,0x809,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define DeleteMyFile 9
#define ENUMIDT CTL_CODE(FILE_DEVICE_UNKNOWN,0x80A,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define EnumIDT 10
#define ENUMGDT CTL_CODE(FILE_DEVICE_UNKNOWN,0x80B,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define EnumGDT 11
#define ENUMSSDT CTL_CODE(FILE_DEVICE_UNKNOWN,0x80C,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define EnumSSDT 12
#define ENUMREG CTL_CODE(FILE_DEVICE_UNKNOWN,0x80D,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define EnumReg 13
#define CREATEREGKEY CTL_CODE(FILE_DEVICE_UNKNOWN,0x80E,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define CreateRegKey 14
#define DELETEREGKEY CTL_CODE(FILE_DEVICE_UNKNOWN,0x80F,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define DeleteRegKey 15
#define SYSHOOK CTL_CODE(FILE_DEVICE_UNKNOWN,0x810,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define SysHook 16
#define RELOADKERNEL CTL_CODE(FILE_DEVICE_UNKNOWN,0x811,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define ReloadKernel 17
#define OBJECTHOOKFILE CTL_CODE(FILE_DEVICE_UNKNOWN,0x812,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define ObjectHookFile 18
#define OBJECTHOOKPROCESS CTL_CODE(FILE_DEVICE_UNKNOWN,0x813,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define ObjectHookProcess 19
#define CHECKINLINEHOOK CTL_CODE(FILE_DEVICE_UNKNOWN,0x814,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define CheckInLineHook 20
#define GETPDB CTL_CODE(FILE_DEVICE_UNKNOWN,0x815,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
#define GetPDB 21
#define GetPDB2 22
#define SSDTHOOKDELETEFILE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x816, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define SSDThookDeleteFile 23 
#define Close 0


void ContolInfomation();
void GetSymbol(DWORD NtAddress, DWORD FunAdd_Name, DWORD choose);
SIZE_T GetSymAddress(HANDLE hProcess, const char* pszName);
BOOL GetSymName(HANDLE hProcess, SIZE_T nAddress, CHAR** strName);